/* Audio Library for Teensy 3.X / i.MX RT
 * Copyright (c) 2026 Nicholas Newdigate
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice, development funding notice, and this
 * permission notice shall be included in all copies or substantial
 * portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

// Audio graph sink that streams to a USB Audio Class 1.0 device attached to
// the RT1176's USB host port, via USBHost_t36's USBAudioOut driver.
//
// Clocking: this node owns the graph's clock, but the clock is the FIFO
// level, not the USB frame counter. That distinction matters.
//
// AudioOutputI2S can pace the graph off its DMA interrupt because that
// interrupt IS the sink's hardware clock -- samples leave at exactly the rate
// it fires. USB is not like that. The 1 kHz SOF is generated by *this* host,
// off the RT1176's own oscillator, while an asynchronous device's DAC runs on
// the device's oscillator. That is what "asynchronous" means. Pacing the graph
// off SOF ticks would be pacing off the wrong clock: rock-steady by our
// reckoning, and slowly wrong against the device, until the FIFO parks at one
// end and stays there.
//
// So the pacing signal is FIFO occupancy. The FIFO drains at whatever rate USB
// is really sending, which (once feedback controls packet sizing) is the
// device's true rate, so the graph tracks the device automatically. The FIFO
// is the elastic element and its level is the error signal -- no resampling.
//
// Occupancy is held near a setpoint rather than simply "run whenever there is
// room". Running on any free space drives the FIFO toward full, which both
// maximises latency and leaves no headroom in the direction where the device
// wants MORE than nominal. Asynchronous operation needs headroom both ways.
//
// Constraint: this holds only while USB is the single hardware-clocked node in
// the graph. Adding AudioInputI2S or AudioOutputI2S introduces a second, truly
// independent oscillator, and one side must then be rate-converted (the fork's
// Resampler). That is a different design, not a tweak -- so do not combine
// them and expect this to keep working.
//
// Rate: enforced in the constructor rather than documented. See the .cpp.

#ifndef output_usbhost_h_
#define output_usbhost_h_

#include "Arduino.h"
#include "AudioStream.h"
#include <USBHost_t36.h>

class AudioOutputUSBHost : public AudioStream
{
public:
	AudioOutputUSBHost(USBAudioOut &usb);
	virtual void update(void);

	// Blocks dropped because the FIFO was full when update() ran. Non-zero
	// means the graph is producing faster than USB is consuming, which
	// should not happen while USB owns the clock -- if it does, something
	// else is also pending the audio interrupt.
	uint32_t dropped(void) const { return blocks_dropped; }

	// Samples the FIFO is held near. One block is AUDIO_BLOCK_SAMPLES frames,
	// so three blocks of stereo is about 8 ms at 48 kHz -- enough to absorb
	// the one-block pacing jitter with room for feedback corrections either
	// way, without carrying the FIFO's full 42 ms of latency.
	static const uint32_t FIFO_TARGET_SAMPLES = AUDIO_BLOCK_SAMPLES * 2 * 3;

	// The rate this node runs the graph at, and therefore the rate it
	// configures USBAudioOut for.
	static const uint32_t GRAPH_RATE = (uint32_t)AUDIO_SAMPLE_RATE_EXACT;

private:
	static void frame_consumed(void);

	USBAudioOut &audio;
	audio_block_t *inputQueueArray[2];
	uint32_t blocks_dropped;

	static AudioOutputUSBHost *instance;
	static bool update_responsibility;
};

#endif
